remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
minimal_mistakes_skin: dark

atom_feed:
  hide: true

search: true
lunr:
  search_within_pages: true

include:
  - _pages

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

title: &name "Engineering 2 The Future" # &name is a YAML anchor
email: e2thefuture@gmail.com
github_username: e2thefuture
logo: /logo.png

social:
  type: Organization
  links:
    - "https://discord.gg/bGAzdPUd8M"


# Site Author
author:
  name: *name # *name is a YAML reference pointing to the &anchor earlier
  avatar: "/logo.png"
  bio: "Engineering 2 the Future is a student-led club dedicated to providing free classes and seminars, allowing youth to learn and explore the world of Engineering. Our teachers encourage students to focus on not only the concepts but also applications of Engineering and help them to become creative and skilled members of society."
  location: "Somewhere, USA"
  links:
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/bGAzdPUd8M"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/e2thefuture"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/engineering2tf"

footer:
  links:
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/bGAzdPUd8M"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/e2thefuture"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/engineering2tf"
